name:                Harper
version:             0.1.0.0
github:              "V0ldek/Harper"
license:             MIT
author:              "Mateusz Gienieczko"
maintainer:          ""
copyright:           "2020 Mateusz Gienieczko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/V0ldek/Harper#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 0.6
- mtl >= 2.2 && < 2.3
- containers >= 0.6 && < 0.7
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && < 1.5

library:
  source-dirs: src

executables:
  Harper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Harper

tests:
  Harper-test:
    main:                Spec.hs
    source-dirs:         test/Harper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Harper
    - HUnit
    - test-framework
    - test-framework-hunit
  OutputM-test:
    main:                Spec.hs
    source-dirs:         test/OutputM
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Harper
    - HUnit
    - test-framework
    - test-framework-hunit