name:                Harper
version:             0.1.0.0
github:              "V0ldek/Harper"
license:             MIT
author:              "Mateusz Gienieczko"
maintainer:          ""
copyright:           "2020 Mateusz Gienieczko"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/V0ldek/Harper#readme>

dependencies:
- base
- array
- mtl
- containers
- directory
- filepath

library:
  source-dirs: src

executables:
  harper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Harper

tests:
  Harper-test:
    main:                Spec.hs
    source-dirs:         test/Harper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Harper
    - HUnit
    - test-framework
    - test-framework-hunit
  OutputM-test:
    main:                Spec.hs
    source-dirs:         test/OutputM
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Harper
    - HUnit
    - test-framework
    - test-framework-hunit